/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotCompletedImport } from './routes/notCompleted'
import { Route as HelpImport } from './routes/help'
import { Route as GameImport } from './routes/game'
import { Route as IndexImport } from './routes/index'
import { Route as ResultHasWonImport } from './routes/result.$hasWon'

// Create/Update Routes

const NotCompletedRoute = NotCompletedImport.update({
  id: '/notCompleted',
  path: '/notCompleted',
  getParentRoute: () => rootRoute,
} as any)

const HelpRoute = HelpImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRoute,
} as any)

const GameRoute = GameImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResultHasWonRoute = ResultHasWonImport.update({
  id: '/result/$hasWon',
  path: '/result/$hasWon',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpImport
      parentRoute: typeof rootRoute
    }
    '/notCompleted': {
      id: '/notCompleted'
      path: '/notCompleted'
      fullPath: '/notCompleted'
      preLoaderRoute: typeof NotCompletedImport
      parentRoute: typeof rootRoute
    }
    '/result/$hasWon': {
      id: '/result/$hasWon'
      path: '/result/$hasWon'
      fullPath: '/result/$hasWon'
      preLoaderRoute: typeof ResultHasWonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/help': typeof HelpRoute
  '/notCompleted': typeof NotCompletedRoute
  '/result/$hasWon': typeof ResultHasWonRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/help': typeof HelpRoute
  '/notCompleted': typeof NotCompletedRoute
  '/result/$hasWon': typeof ResultHasWonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/help': typeof HelpRoute
  '/notCompleted': typeof NotCompletedRoute
  '/result/$hasWon': typeof ResultHasWonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game' | '/help' | '/notCompleted' | '/result/$hasWon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game' | '/help' | '/notCompleted' | '/result/$hasWon'
  id: '__root__' | '/' | '/game' | '/help' | '/notCompleted' | '/result/$hasWon'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  HelpRoute: typeof HelpRoute
  NotCompletedRoute: typeof NotCompletedRoute
  ResultHasWonRoute: typeof ResultHasWonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  HelpRoute: HelpRoute,
  NotCompletedRoute: NotCompletedRoute,
  ResultHasWonRoute: ResultHasWonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/game",
        "/help",
        "/notCompleted",
        "/result/$hasWon"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/game": {
      "filePath": "game.tsx"
    },
    "/help": {
      "filePath": "help.tsx"
    },
    "/notCompleted": {
      "filePath": "notCompleted.tsx"
    },
    "/result/$hasWon": {
      "filePath": "result.$hasWon.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
